name: ğŸ Generate Snake Animation GIF

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch:       # Permite execuÃ§Ã£o manual no GitHub Actions

jobs:
  generate:
    name: Snake Animation Job
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do repositÃ³rio
        uses: actions/checkout@v3

      - name: ğŸ› ï¸ Criar pasta dist
        run: mkdir -p dist

      - name: ğŸ Gerar animaÃ§Ã£o Snake GIF
        uses: Platane/snk@v3
        with:
          github_user_name: AmaroMiranda
          gif_out_path: dist/github-contribution-grid-snake.gif
          color_snake: '#36BCF7'
          color_dots: '#CCCCCC,#BBBBBB,#999999,#666666,#333333'

      - name: ğŸ“¤ Enviar GIF para o branch output
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
